export  const actions = {
    //BRAND_REGISTER
    BRAND_REGISTER_REQUEST: "BRAND_REGISTER_REQUEST",
    BRAND_REGISTER_SUCCESS: "BRAND_REGISTER_SUCCESS",
    BRAND_REGISTER_FAIL: "BRAND_REGISTER_FAIL",
    BRAND_REGISTER_RESET: "BRAND_REGISTER_RESET",
    //BRAND_UPDATE
    BRAND_UPDATE_REQUEST: "BRAND_UPDATE_REQUEST",
    BRAND_UPDATE_SUCCESS: "BRAND_UPDATE_SUCCESS",
    BRAND_UPDATE_FAIL: "BRAND_UPDATE_FAIL",
    BRAND_UPDATE_RESET: "BRAND_UPDATE_RESET",
    //BRAND_LIST
    BRAND_LIST_REQUEST: "BRAND_LIST_REQUEST",
    BRAND_LIST_SUCCESS: "BRAND_LIST_SUCCESS",
    BRAND_LIST_FAIL: "BRAND_LIST_FAIL",
    BRAND_LIST_RESET: "BRAND_LIST_RESET",
    //BRAND_DETAILS
    BRAND_DETAILS_REQUEST: "BRAND_DETAILS_REQUEST",
    BRAND_DETAILS_SUCCESS: "BRAND_DETAILS_SUCCESS",
    BRAND_DETAILS_FAIL: "BRAND_DETAILS_FAIL",
    BRAND_DETAILS_RESET: "BRAND_DETAILS_RESET",
    //BRAND_DELETE
    BRAND_DELETE_REQUEST: "BRAND_DELETE_REQUEST",
    BRAND_DELETE_SUCCESS: "BRAND_DELETE_SUCCESS",
    BRAND_DELETE_FAIL: "BRAND_DELETE_FAIL",
    BRAND_DELETE_RESET: "BRAND_DELETE_RESET",
  };
  