export  const actions = {
    //BRAND_CREATE
    BRAND_CREATE_REQUEST: "BRAND_CREATE_REQUEST",
    BRAND_CREATE_SUCCESS: "BRAND_CREATE_SUCCESS",
    BRAND_CREATE_FAIL: "BRAND_CREATE_FAIL",
    BRAND_CREATE_RESET: "BRAND_CREATE_RESET",
    //BRAND_EDIT
    BRAND_EDIT_REQUEST: "BRAND_EDIT_REQUEST",
    BRAND_EDIT_SUCCESS: "BRAND_EDIT_SUCCESS",
    BRAND_EDIT_FAIL: "BRAND_EDIT_FAIL",
    BRAND_EDIT_RESET: "BRAND_EDIT_RESET",
    //BRAND_LIST
    BRAND_LIST_REQUEST: "BRAND_LIST_REQUEST",
    BRAND_LIST_SUCCESS: "BRAND_LIST_SUCCESS",
    BRAND_LIST_FAIL: "BRAND_LIST_FAIL",
    BRAND_LIST_RESET: "BRAND_LIST_RESET",
    //BRAND_DETAILS
    BRAND_DETAILS_REQUEST: "BRAND_DETAILS_REQUEST",
    BRAND_DETAILS_SUCCESS: "BRAND_DETAILS_SUCCESS",
    BRAND_DETAILS_FAIL: "BRAND_DETAILS_FAIL",
    BRAND_DETAILS_RESET: "BRAND_DETAILS_RESET",
    //BRAND_DETAILS
    BRAND_DETAILS_REQUEST: "BRAND_DETAILS_REQUEST",
    BRAND_DETAILS_SUCCESS: "BRAND_DETAILS_SUCCESS",
    BRAND_DETAILS_FAIL: "BRAND_DETAILS_FAIL",
    BRAND_DETAILS_RESET: "BRAND_DETAILS_RESET",
  };
  