export  const actions = {
    //BRANCH_CREATE
    BRANCH_CREATE_REQUEST: "BRANCH_CREATE_REQUEST",
    BRANCH_CREATE_SUCCESS: "BRANCH_CREATE_SUCCESS",
    BRANCH_CREATE_FAIL: "BRANCH_CREATE_FAIL",
    BRANCH_CREATE_RESET: "BRANCH_CREATE_RESET",
    //BRANCH_EDIT
    BRANCH_EDIT_REQUEST: "BRANCH_EDIT_REQUEST",
    BRANCH_EDIT_SUCCESS: "BRANCH_EDIT_SUCCESS",
    BRANCH_EDIT_FAIL: "BRANCH_EDIT_FAIL",
    BRANCH_EDIT_RESET: "BRANCH_EDIT_RESET",
    //BRANCH_LIST
    BRANCH_LIST_REQUEST: "BRANCH_LIST_REQUEST",
    BRANCH_LIST_SUCCESS: "BRANCH_LIST_SUCCESS",
    BRANCH_LIST_FAIL: "BRANCH_LIST_FAIL",
    BRANCH_LIST_RESET: "BRANCH_LIST_RESET",
    //BRANCH_DETAILS
    BRANCH_DETAILS_REQUEST: "BRANCH_DETAILS_REQUEST",
    BRANCH_DETAILS_SUCCESS: "BRANCH_DETAILS_SUCCESS",
    BRANCH_DETAILS_FAIL: "BRANCH_DETAILS_FAIL",
    BRANCH_DETAILS_RESET: "BRANCH_DETAILS_RESET",
    //BRANCH_DETAILS
    BRANCH_DETAILS_REQUEST: "BRANCH_DETAILS_REQUEST",
    BRANCH_DETAILS_SUCCESS: "BRANCH_DETAILS_SUCCESS",
    BRANCH_DETAILS_FAIL: "BRANCH_DETAILS_FAIL",
    BRANCH_DETAILS_RESET: "BRANCH_DETAILS_RESET",
  };
  