export  const actions = {
    //PRODUCT_CREATE
    PRODUCT_CREATE_REQUEST: "PRODUCT_CREATE_REQUEST",
    PRODUCT_CREATE_SUCCESS: "PRODUCT_CREATE_SUCCESS",
    PRODUCT_CREATE_FAIL: "PRODUCT_CREATE_FAIL",
    PRODUCT_CREATE_RESET: "PRODUCT_CREATE_RESET",
    //PRODUCT_EDIT
    PRODUCT_EDIT_REQUEST: "PRODUCT_EDIT_REQUEST",
    PRODUCT_EDIT_SUCCESS: "PRODUCT_EDIT_SUCCESS",
    PRODUCT_EDIT_FAIL: "PRODUCT_EDIT_FAIL",
    PRODUCT_EDIT_RESET: "PRODUCT_EDIT_RESET",
    //PRODUCT_LIST
    PRODUCT_LIST_REQUEST: "PRODUCT_LIST_REQUEST",
    PRODUCT_LIST_SUCCESS: "PRODUCT_LIST_SUCCESS",
    PRODUCT_LIST_FAIL: "PRODUCT_LIST_FAIL",
    PRODUCT_LIST_RESET: "PRODUCT_LIST_RESET",
    //PRODUCT_DETAILS
    PRODUCT_DETAILS_REQUEST: "PRODUCT_DETAILS_REQUEST",
    PRODUCT_DETAILS_SUCCESS: "PRODUCT_DETAILS_SUCCESS",
    PRODUCT_DETAILS_FAIL: "PRODUCT_DETAILS_FAIL",
    PRODUCT_DETAILS_RESET: "PRODUCT_DETAILS_RESET",
    //PRODUCT_DELETE
    PRODUCT_DELETE_REQUEST: "PRODUCT_DELETE_REQUEST",
    PRODUCT_DELETE_SUCCESS: "PRODUCT_DELETE_SUCCESS",
    PRODUCT_DELETE_FAIL: "PRODUCT_DELETE_FAIL",
    PRODUCT_DELETE_RESET: "PRODUCT_DELETE_RESET",
    //PRODUCT_REVIEW
    PRODUCT_REVIEW_REQUEST: "PRODUCT_REVIEW_REQUEST",
    PRODUCT_REVIEW_SUCCESS: "PRODUCT_REVIEW_SUCCESS",
    PRODUCT_REVIEW_FAIL: "PRODUCT_REVIEW_FAIL",
    PRODUCT_REVIEW_RESET: "PRODUCT_REVIEW_RESET",
  };
  