# Generated by Django 3.2 on 2021-07-05 18:19

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branchId', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('branchName', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brandId', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('brandName', models.CharField(max_length=128)),
                ('brandDesc', models.CharField(max_length=1024)),
                ('brandPic', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('brandRegDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('catId', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('catName', models.CharField(max_length=32)),
                ('catDesc', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('cityId', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('cityName', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('countryId', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('countryName', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('presId', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('presName', models.CharField(max_length=32)),
                ('presContNet', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('presUnit', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('prodId', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('prodName', models.CharField(max_length=128)),
                ('prodPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('prodDesc', models.CharField(max_length=1024)),
                ('prodPic', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('prodRegDate', models.DateTimeField(auto_now_add=True)),
                ('catId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.categorie')),
                ('marcId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.brand')),
                ('presId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.presentation')),
                ('sucId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('revId', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('revName', models.CharField(max_length=128)),
                ('revRating', models.IntegerField()),
                ('revComment', models.CharField(max_length=1024)),
                ('revDate', models.DateTimeField(auto_now_add=True)),
                ('prodId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.products')),
                ('usrId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orderId', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('orderName', models.CharField(max_length=128)),
                ('orderDate', models.DateTimeField(auto_now_add=True)),
                ('usrId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('mprodId', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('mprodCantidad', models.IntegerField()),
                ('mcanId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.orders')),
                ('prodId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.products')),
            ],
        ),
        migrations.CreateModel(
            name='Domicile',
            fields=[
                ('domId', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('domDomicilio', models.CharField(max_length=128)),
                ('domPostal', models.CharField(max_length=8)),
                ('cityId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.ciudad')),
            ],
        ),
        migrations.AddField(
            model_name='ciudad',
            name='countryId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.pais'),
        ),
        migrations.AddField(
            model_name='branch',
            name='domId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.domicile'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addname', models.CharField(max_length=128)),
                ('domId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.domicile')),
                ('usrId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
