# Generated by Django 3.2 on 2021-07-06 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210705_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='prodRegDate',
        ),
    ]
