# Generated by Django 3.2 on 2021-07-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_products_prodregdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='numReviews',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Number of Reviews'),
        ),
        migrations.AddField(
            model_name='products',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Rating'),
        ),
    ]
